apiVersion: v1
kind: Service
metadata:
  name: video-recorder
  namespace: video-recorder
  labels:
    app: video-recorder
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: video-recorder
